-- Cadastro de ex-jogadores (Não Membros) para histórico
INSERT INTO members (name, email, is_active, level) VALUES
('Ritir', 'ritir.historico@rachaldeira.com.br', false, 1),
('Memphis', 'memphis.historico@rachaldeira.com.br', false, 1),
('Suricato', 'suricato.historico@rachaldeira.com.br', false, 1),
('Ninho', 'ninho.historico@rachaldeira.com.br', false, 1),
('Barba', 'barba.historico@rachaldeira.com.br', false, 1),
('Marlon', 'marlon.historico@rachaldeira.com.br', false, 1),
('Railing', 'railing.historico@rachaldeira.com.br', false, 1),
('JM', 'jm.historico@rachaldeira.com.br', false, 1),
('Miguel', 'miguel.historico@rachaldeira.com.br', false, 1),
('Bambino', 'bambino.historico@rachaldeira.com.br', false, 1),
('Tetéu', 'teteu.historico@rachaldeira.com.br', false, 1),
('Zulu', 'zulu.historico@rachaldeira.com.br', false, 1),
('Thierry', 'thierry.historico@rachaldeira.com.br', false, 1),
('Caíque', 'caique.historico@rachaldeira.com.br', false, 1),
('Donas', 'donas.historico@rachaldeira.com.br', false, 1),
('Bruno Lima', 'brunolima.historico@rachaldeira.com.br', false, 1),
('Molão', 'molao.historico@rachaldeira.com.br', false, 1),
('Ilso', 'ilso.historico@rachaldeira.com.br', false, 1),
('Will', 'will.historico@rachaldeira.com.br', false, 1),
('Luk', 'luk.historico@rachaldeira.com.br', false, 1),
('Bi', 'bi.historico@rachaldeira.com.br', false, 1),
('Lucas Ricci', 'lucasricci.historico@rachaldeira.com.br', false, 1),
('Dudu', 'dudu.historico@rachaldeira.com.br', false, 1),
('Leandro', 'leandro.historico@rachaldeira.com.br', false, 1),
('Matheus Amorim', 'matheusamorim.historico@rachaldeira.com.br', false, 1),
('João Braz', 'joaobraz.historico@rachaldeira.com.br', false, 1),
('Di Maria', 'dimaria.historico@rachaldeira.com.br', false, 1),
('César', 'cesar.historico@rachaldeira.com.br', false, 1),
('Rapini', 'rapini.historico@rachaldeira.com.br', false, 1),
('Ramon', 'ramon.historico@rachaldeira.com.br', false, 1),
('Eliel', 'eliel.historico@rachaldeira.com.br', false, 1),
('Patrick', 'patrick.historico@rachaldeira.com.br', false, 1),
('Danilo', 'danilo.historico@rachaldeira.com.br', false, 1),
('José', 'jose.historico@rachaldeira.com.br', false, 1),
('Felipe', 'felipe.historico@rachaldeira.com.br', false, 1)
ON CONFLICT (email) DO NOTHING;
